name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run tests
        run: python -m pytest -v

docker-build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t telco-churn-app .

      - name: Log in and push to Docker Hub
        if: github.event_name == 'push'
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker tag telco-churn-app ${{ secrets.DOCKERHUB_USERNAME }}/telco-churn-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/telco-churn-app:latest


deploy-to-lightsail:
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Trigger Lightsail deployment
        run: |
          aws lightsail create-container-service-deployment \
            --service-name telco-churn-service \
            --containers '{"telco-churn":{"image":"kayodenet/telco-churn-app:latest","ports":{"8000":"HTTP"}}}' \
            --public-endpoint '{"containerName":"telco-churn","containerPort":8000,"healthCheck":{"path":"/"}}'